# Generated by Django 4.1 on 2022-10-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donater',
            name='bloodgroup',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donater',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donater',
            name='ph_no',
            field=models.BigIntegerField(),
        ),
    ]
