# Generated by Django 4.1 on 2022-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('ph_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('bloodgroup', models.CharField(max_length=10)),
            ],
        ),
    ]
