# Generated by Django 4.1 on 2022-10-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_stockinput_rename_donater_donate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donate',
            new_name='donater',
        ),
        migrations.DeleteModel(
            name='stockinput',
        ),
    ]
