# Generated by Django 4.1 on 2022-10-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_requestclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestclass',
            old_name='address_request',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='birthday_request',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='bloodgroup_request',
            new_name='bloodgroup',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='email_request',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='first_name_request',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='last_name_request',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='requestclass',
            old_name='ph_no_request',
            new_name='ph_no',
        ),
    ]
