# Generated by Django 4.1 on 2022-10-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_rename_address_request_requestclass_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donater',
            old_name='birthday',
            new_name='birthyear',
        ),
    ]
