# Generated by Django 4.1 on 2022-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_rename_birthday_donater_birthyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestclass',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='requestclass',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='requestclass',
            name='last_name',
        ),
        migrations.AddField(
            model_name='requestclass',
            name='birthyear',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
